### PR TITLE
Devfest2019 urgent changes

### PR DESCRIPTION
**Pull request by YaguraStation**
With the announcement, some quick changes for the 2019 event. More to come later. 

* Updated to the latest version (upstream/master)
* rudimentary changes for 2019 in settings
* add 2019 images

PS: Forgot I changed my email recently - commits don't resolve to GitHub user.

### CODE REVIEW

**Comment by riggaroo** [comment]
@YaguraStation Sure. I think we can actually transfer this repo to you - or a GDG organisation?

**Comment by riggaroo** [comment]
Did you manage to deploy it?

**Comment by YaguraStation** [comment]
No, don't have necessary permissions as _Develop Admin_ in the Firebase project, since the app also contains functions. See [Cloud Functions for Firebase permissions](https://firebase.google.com/docs/projects/iam/permissions/#functions).

Independent from above, I've created the org [gdg-southafrica](https://github.com/organizations/gdg-southafrica) and have invited you. You could move the repo to there and I'll add the gang. 

Thanks a bunch!

**Comment by riggaroo** [comment]
I've upgraded your permissions to Editor. Let me know if you still can't deploy. 
I can't see an invite for that organisation yet.

**Comment by YaguraStation** [comment]
Awesome, thanks. Deployed. I see there are many small things to be mended, but will continue once the repo is in the new org. 

I've sent out invites during org creation (also to PJ and Jacques) which didn't seem to work. Have sent them out once more.

**Pull request merged**
